config/routes.rb
Rails.application.routes.draw do

  root 'basic_pages#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  get '/create_post', to: 'posts#new'
  post '/create_post', to: 'posts#create'
  get '/all_posts', to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  before_create :remember

  has_secure_password

  class << self
    # Create a token
    def new_token
      SecureRandom.urlsafe_base64
    end

    # Convert to digest
    def digest(string)
      Digest::SHA1.hexdigest(string.to_s)
    end
  end

  def remember
    self.remember_token = User.digest(User.new_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in?

  def log_in(user)
    remember_token = User.digest(User.new_token)
    user.update_attribute(:remember_token, remember_token)
    cookies.permanent.signed[:remember_token] = remember_token
    current_user = user
  end

  def log_out
    current_user.update_attribute(:remember_token, nil)
    current_user = nil
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  # Handling the current user

  def current_user
    if cookies[:remember_token]
      @current_user ||= User.find_by(remember_token: cookies.signed[:remember_token])
    end
  end

  def current_user=(user)
    @current_user = user
  end
end

app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :logged_in?, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    puts @current_user.name
    @post = Post.new(body: params[:post][:body], author: params[:author])
    if @post.save
      redirect_to all_posts_path
    else
      flash.now[:danger] = "Post creation failed"
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = "Login failed"
      render 'new'
    end
  end

  def delete
    log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/views/basic_pages/home.html.erb
<%= render 'layouts/header'%>

<h1 class="club-name">Members Only Club</h1>

<div id="info">
  <p>This is the super secret exclusively select Members Only Club.</p>
  <p>Here our members have the exclusive privilege of posting to other members of the club.</p>
  <p>Anyone can see member posts, but only members will see who wrote each post.</p>
  <p>Want to join? <span class="too-bad">TOO BAD!</span> We are not accepting any new members.</p>
</div>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="nav-container">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Posts", all_posts_path %></li>
      <% if cookies[:remember_token].nil? %>
      <li><%= link_to "Login", login_path %></li>
      <% else %>
      <li><%= link_to "New Post", create_post_path %></li>
      <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members Only Club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash-container">
      <% flash.each do |flash_type, message|%>
        <div class="alert alert-<%= flash_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render 'layouts/header'%>

<h1>All Posts</h1>

<% @posts.each do |post| %>
  <div class="post">
    <p><%= post.body %></p>
    <% if !cookies.signed[:remember_token].nil? %>
      <p>Author: <%= post.author %></p> 
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for(@post, url: create_post_path) do |f| %>
  
  <%= f.label :body %><br>
  <%= f.text_field :body %><br>

  <%= hidden_field_tag :author, @current_user.name %>

  <%= f.submit "Create Post" %>

<% end %>